CREATE TYPE gender_type AS ENUM ('male', 'female');

CREATE Table IF NOT EXISTS customers (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(50) NOT NULL,
    gender gender_type NOT NULL,
    phone VARCHAR(15) NOT NULL,
    address TEXT NOT NULL
);

ALTER TABLE customers
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE customers
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

DROP TABLE IF EXISTS customers;