runtime: nodejs
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '20'

manual_scaling:
  instances: 1

env_variables:
  NODE_ENV: 'production'

beta_settings:
  cloud_sql_instances: fajri-learning-workspace:us-central1:postgres-binar-fa