name: Node.js CI

on:
  push:
    branches:
      - main  # Only run CI on pushes to the "dev" branch
  pull_request:
    branches:
      - main  # Run CI on pull requests to the "dev" branch

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]  # Test against multiple Node.js versions

    env:
      IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
      IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
      IMAGEKIT_URL_ENDPOINT: ${{ secrets.IMAGEKIT_URL_ENDPOINT }}

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 4: Lint code
      - name: Lint code
        run: pnpm lint

      # Step 5: Run tests
      - name: Run tests
        env:
          NODE_ENV: test
        run: pnpm test

      # Step 6: Integrasion Coverage Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info    # Jalur ke file lcov coverage, pastikan jalur ini benar
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }} # Hanya perlu untuk repositori private

      # Step 7: Deploy to App Engine
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: pull request
        run: |
          cd ~/F-BEE24001186-km7-faj-basic-banking-system-ch2
          git pull origin main

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy app.yaml